name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Install lcov"
      run: sudo apt-get install -y lcov
    - name: "Create build dir"
      run: mkdir build
    - name: "Invoke cmake"
      working-directory: "build"
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DENABLE_TEST=ON
    - name: "Build"
      working-directory: "build"
      run: cmake --build .
    - name: "Create baseline coverage"
      working-directory: "build"
      run: lcov --directory . --capture --initial --output-file coverage_base.info
    - name: "Invoke tests"
      working-directory: "build"
      run: "./bin/hope-test"
    - name: "Collect coverage"
      working-directory: "build"
      run: |
        lcov --directory . --capture --output-file coverage_test.info
        lcov --add-tracefile coverage_base.info --add-tracefile coverage_test.info --output-file coverage.info
        rm coverage_base.info
        rm coverage_test.info
        lcov --remove coverage.info "/usr/*" --output-file coverage.info
        lcov --remove coverage.info "*/build/*" --output-file coverage.info
        lcov --remove coverage.info "*/tests/*" --output-file coverage.info
        lcov --remove coverage.info "*/examples/*" --output-file coverage.info
        mv coverage.info ..
        rm -rf *
        mv ../coverage.info .
    - name: Upload coverage
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} 
