name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Install lcov"
      run: sudo apt-get install -y lcov
    - name: "Create build dir"
      run: mkdir build
    - name: "Invoke cmake"
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DENABLE_TEST=ON
      working-directory: "build"
    - name: "Build"
      run: cmake --build .
      working-directory: "build"
    - name: "Create baseline coverage"
      run: lcov --directory . --capture --initial --output-file coverage_base.info
      working-directory: "build"
    - name: "Invoke tests"
      run: "./hope-test"
      working-directory: "build/bin"
    - name: "Combine coverage"
      run: |
        lcov --add-tracefile coverage_base.info --add-tracefile coverage_test.info --output-file coverage.info
        rm coverage_base.info
        rm coverage_test.info
        lcov --remove coverage.info "/usr/*" --output-file coverage.info
        lcov --remove coverage.info "*/build/*" --output-file coverage.info
        lcov --remove coverage.info "*/tests/*" --output-file coverage.info
        lcov --remove coverage.info "*/examples/*" --output-file coverage.info
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
