name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Install lcov"
      run: sudo apt-get install -y lcov
    - name: "Create build dir"
      run: mkdir build
    - name: "Invoke cmake"
      working-directory: "build"
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DENABLE_TEST=ON
    - name: "Build"
      working-directory: "build"
      run: cmake --build .
    - name: "Invoke tests"
      working-directory: "build"
      run: "./bin/hope-test"
    - name: "Collect coverage"
      working-directory: "build"
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info "/usr/*" -o coverage.info
        lcov --remove coverage.info "*/build/*" -o coverage.info
        lcov --remove coverage.info "*/test/*" -o coverage.info
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
