name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Create build dir"
      run: mkdir build
    - name: "Invoke cmake"
      run: cmake ..
      working-directory: "build"
    
